name: screenshot X with playwright
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python3 -m venv .venv
      - run: source .venv/bin/activate
      - run: pip install -r requirements.txt
      - run: playwright install --with-deps
      - run: python twitter-x.py
      - uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/
      - uses: actions/upload-artifact@v4
        with:
          name: stateFiles
          path: stateFiles/
      - uses: actions/download-artifact@v4
        with:
          name: stateFiles
      
